/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import Main.Peminjaman;
import Main.PeminjamanPK;
import Main.Skripsi;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saintek1
 */
public class PerbaruiPeminjaman extends javax.swing.JPanel {

    Connection conn = null;
    
    public void peringatan(String pesan) {
        Component rootPane = null;
        JOptionPane.showMessageDialog(rootPane, pesan);
        try {
            conn = DriverManager.getConnection("jdbc:postgresql://localhost:5433/Akhir", "postgres", "uinsa");
        } catch (SQLException ex) {
            Logger.getLogger(PerbaruiBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    ArrayList<Test> dataTest;
    
    private int masukkanData(Connection conn, String Id_pegawai, String Id_anggota, String Id_pinjam, String tgl_pinjam) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("INSERT INTO peminjaman (Id_pegawai,Id_anggota,Id_pinjam,tgl_pinjam) VALUES(?,?,?,?)");
        pst.setString(1, Id_pegawai);
        pst.setString(2, Id_anggota);
        pst.setString(3, Id_pinjam);
        pst.setString(4, tgl_pinjam);
        return pst.executeUpdate();
    }
    
    private int editData(Connection conn, String Id_pegawai, String Id_anggota, String Id_pinjam, String tgl_pinjam) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("UPDATE peminjaman set Id_pegawai = ?,Id_anggota = ?,tgl_pinjam = ? where Id_pinjam = ? ");
        pst.setString(2, Id_pegawai);
        pst.setString(3, Id_anggota);
        pst.setString(1, Id_pinjam);
        pst.setString(4, tgl_pinjam);
        return pst.executeUpdate();
    }
    
    private int hapusData(Connection conn, String Id_pinjam) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("DELETE From peminjaman where Id_pinjam = ? ");
        pst.setString(1, Id_pinjam);
        return pst.executeUpdate();
    }
    
    private void TampilP(Connection conn) {
        dataTest.clear();
        try {
            String sql = "select * from peminjaman";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Test data = new Test();
                data.setId_pegawai(String.valueOf(rs.getObject(1)));
                data.setId_anggota(String.valueOf(rs.getObject(2)));
                data.setId_pinjam(String.valueOf(rs.getObject(3)));
                data.setTgl_pinjam(String.valueOf(rs.getObject(4)));
                dataTest.add(data);
            }
            DefaultTableModel model = (DefaultTableModel) jTableP.getModel();
            model.setRowCount(0);
            for (Test data : dataTest) {

                Object[] baris = new Object[4];
                baris[0] = data.getId_pegawai();
                baris[1] = data.getId_anggota();
                baris[2] = data.getId_pinjam();
                baris[3] = data.getTgl_pinjam();

                model.addRow(baris);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PeminjamanP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Creates new form PerbaruiPeminjaman
     */
    
    public PerbaruiPeminjaman() {
        try {
            dataTest = new ArrayList<>();
            initComponents();
            conn = DriverManager.getConnection("jdbc:postgresql://localhost:5433/Akhir", "postgres", "uinsa");
            TampilP(conn);
        } catch (SQLException ex) {
            Logger.getLogger(PeminjamanP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableP = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIpe = new javax.swing.JTextField();
        jTextFieldIa = new javax.swing.JTextField();
        jTextFieldIpi = new javax.swing.JTextField();
        jTextFieldTgl = new javax.swing.JTextField();
        jButtonInsert = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));
        jPanel1.setForeground(new java.awt.Color(153, 102, 0));

        jTableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_pegawai", "id_anggota", "id_pinjam", "tgl_pinjam"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableP.getTableHeader().setReorderingAllowed(false);
        jTableP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableP);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("id pegawai");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("id anggota");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("id pinjam");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("tgl_pinjam");

        jTextFieldIpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIpeActionPerformed(evt);
            }
        });

        jButtonInsert.setText("insert");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("edit");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldIpe)
                        .addComponent(jTextFieldIa)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextFieldIpi)
                        .addComponent(jTextFieldTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUpdate))
                    .addComponent(jButtonDelete))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInsert)
                            .addComponent(jButtonUpdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDelete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIpeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIpeActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        // TODO add your handling code here:
        String id_pegawai = jTextFieldIpe.getText();
        String id_anggota = jTextFieldIa.getText();
        String id_pinjam = jTextFieldIpi.getText();
        String tgl_pinjam = jTextFieldTgl.getText();
        //
        EntityManager entityManager;
        entityManager = Persistence.createEntityManagerFactory("apkPU").createEntityManager();
        entityManager.getTransaction().begin();
        Peminjaman m = new Peminjaman();
        PeminjamanPK d = new PeminjamanPK();
        d.setIdPegawai(id_pegawai);
        d.setIdAnggota(id_anggota);
        d.setIdPinjam(id_pinjam);
        m.setTglPinjam(tgl_pinjam);
        m.setPeminjamanPK(d);
        entityManager.persist(m);
        entityManager.getTransaction().commit();
        //
            TampilP(conn);
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jTablePMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePMouseClicked
        // TODO add your handling code here:
        int row = jTableP.getSelectedRow();
        jTextFieldIpe.setText(jTableP.getValueAt(row, 0).toString());
        jTextFieldIa.setText(jTableP.getValueAt(row, 1).toString());
        jTextFieldIpi.setText(jTableP.getValueAt(row, 2).toString());
        jTextFieldTgl.setText(jTableP.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTablePMouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
//        String id_pegawai = jTextFieldIpe.getText();
//        String id_anggota = jTextFieldIa.getText();
//        String id_pinjam = jTextFieldIpi.getText();
//        String tgl_pinjam = jTextFieldTgl.getText();
//        //
//        EntityManager em;
//        em = Persistence.createEntityManagerFactory("apkPU").createEntityManager();
//        em.getTransaction().begin();
//        Peminjaman m = em.find(Skripsi.class, id_pinjam);
//        PeminjamanPK d = em.find(Skripsi.class, id_pinjam);
//        d.setIdPegawai(id_pegawai);
//        d.setIdAnggota(id_anggota);
//        d.setIdPinjam(id_pinjam);
//        m.setTglPinjam(tgl_pinjam);
//        m.setPeminjamanPK(d);
//        em.persist(m);
//        em.getTransaction().commit();
        //
            TampilP(conn);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        String id_pinjam = jTextFieldIpi.getText().trim();
        //awal persistence
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("apkPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();
        Peminjaman s = em.find(Peminjaman.class, id_pinjam);
        em.remove(s);
        em.getTransaction().commit();
        // akhir persistence
            TampilP(conn);
    }//GEN-LAST:event_jButtonDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableP;
    private javax.swing.JTextField jTextFieldIa;
    private javax.swing.JTextField jTextFieldIpe;
    private javax.swing.JTextField jTextFieldIpi;
    private javax.swing.JTextField jTextFieldTgl;
    // End of variables declaration//GEN-END:variables
}
